language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
      #- "5.12"
      #- "5.10"

before_install:
  - cpanm --quiet --notest Dist::Zilla
  - dzil authordeps --missing | cpanm --quiet --notest || { cat ~/.cpanm/build.log ; false ; }

install:
  - dzil listdeps --author --missing | cpanm --quiet --notest || { cat ~/.cpanm/build.log ; false ; }

script:
  - dzil test --author --release
